### ISSUE TITLE
Discrepancy Between Reported and Obtained Results

### ISSUE THREAD

**Issue by moeiniamir** [VITA-Group/llm-kick#1]
Hi,

I tried to reproduce the most simple setting: Vicuna-7B quantized using GPTQ on the Factoid-based QA and here are the results I obtain:

| Benchmarks/Models | Vicuna-7B-Original16bit | Vicuna-7B-GPTQ8bit | Vicuna-7B-GPTQ4bit |
| ------------------ | ----------------------- | ------------------- | ------------------- |
| Factoid-based QA   | 60.54%                 | 60.04% (-0.5%)      | 45.95% (-14.59%)    |

Which is very different from the results below deduced from the paper:

| Benchmarks/Models | Vicuna-7B-Original16bit | Vicuna-7B-GPTQ8bit | Vicuna-7B-GPTQ4bit |
| ------------------ | ----------------------- | ------------------- | ------------------- |
| Factoid-based QA   | ?                      | ? (~ -7%)           | ? (~ -36%)          |

I have attached the test outputs for the three runs.

[freebase_16bits_128_group.txt](https://github.com/VITA-Group/llm-kick/files/14932882/freebase_16bits_128_group.txt)

[freebase_8bits_128_group.txt](https://github.com/VITA-Group/llm-kick/files/14932881/freebase_8bits_128_group.txt)

[freebase_4bits_128_group.txt](https://github.com/VITA-Group/llm-kick/files/14932880/freebase_4bits_128_group.txt)

Could you please provide the exact process to reproduce your results?

**Comment by Ajay1994** [comment]
Hello @moeiniamir ,

I re-run the script for 4-bit GPTQ quantized model and attaching my log for first 1000 samples. You can observe that compared to 61.23 of the full precision model, we observe 41.76 absolute performance of 4-bit model.

Note that we are reporting the performance drop in comparison with the dense/full precision model. i.e., 41.76 is around -32% less than 61.23. Even in your results you posted for 4-bit, performance drop is around 24-25% compared to 16bit model (60.54).

Note: Paper reported results are conducted on randomly sampled 5,000 samples from FreebaseQA trainset instead of 1,000 across 3 independent runs with different random seeds for calibration data for GPTQ.

[freebase_4bits_128_group.txt](https://github.com/VITA-Group/llm-kick/files/14967526/freebase_4bits_128_group.txt)

**Comment by moeiniamir** [comment]
Thank you for your answer. I didn't know you are calculating the drop in percentage of the percentage. 
Also, could check if you get the same result for the 8bit model too?
